name: Build Feature Branch Apk

on: [ push, pull_request ]

env:
  SKAINET_COMMIT: 6f61c63

jobs:
  build-job:
    runs-on: ubuntu-latest # enables hardware acceleration in the virtual machine
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Clone and build skainet dependency
        run: |
          git clone https://github.com/sk-ai-net/skainet.git
          cd skainet
          git checkout ${{ env.SKAINET_COMMIT }}
          ./gradlew publishToMavenLocal

      - name: Print git commit variables
        run: |
          echo "TAG: $CURRENT_TAG"

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Build
        run: ./gradlew --stacktrace clean assemble allTests